export type GalleryCategory = 'vitrines' | 'oeuvres' | 'animale' | 'autres' | 'edition-limitee'

export interface GalleryItem {
  id: string
  category: GalleryCategory
  src: string
  alt: string
  title?: string
  description?: string
}

// TODO: Remplacer tous les items par vos vraies images
// Structure des fichiers à créer dans /public/images/gallery/
//   vitrines/  → photos de vos vitrines réalisées
//   oeuvres/   → vos créations personnelles
//   animale/   → visuels liés à la communication animale
//   autres/    → toutes autres créations

export const galleryItems: GalleryItem[] = [
  // --- Vitrines ---
  {
    id: 'v1',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v1.jpg',
    alt: 'Vitrine commerciale',
    title: 'Vitrine 1',
  },
  {
    id: 'v2',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v2.jpg',
    alt: 'Vitrine commerciale 2',
    title: 'Vitrine 2',
  },
  {
    id: 'v3',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v3.jpg',
    alt: 'Vitrine commerciale 3',
    title: 'Vitrine 3',
  },

  {
    id: 'v4',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v4.png',
    alt: 'Vitrine commerciale 4',
    title: 'Vitrine 4',
    description: 'Création vitrine',
  },
  {
    id: 'v5',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v5.png',
    alt: 'Vitrine commerciale 5',
    title: 'Vitrine 5',
    description: 'Création vitrine',
  },
  {
    id: 'v6',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v6.png',
    alt: 'Vitrine commerciale 6',
    title: 'Vitrine 6',
    description: 'Création vitrine',
  },

  {
    id: 'v7',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v7.png',
    alt: 'Vitrine commerciale 7',
    title: 'Vitrine 7',
  },
  {
    id: 'v8',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v8.png',
    alt: 'Vitrine commerciale 8',
    title: 'Vitrine 8',
  },
  {
    id: 'v9',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v9.png',
    alt: 'Vitrine commerciale 9',
    title: 'Vitrine 9',
  },

  {
    id: 'v10',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v10.png',
    alt: 'Vitrine commerciale 10',
    title: 'Vitrine 10',
    description: 'Création vitrine',
  },
  {
    id: 'v11',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v11.png',
    alt: 'Vitrine commerciale 11',
    title: 'Vitrine 11',
    description: 'Création vitrine',
  },
  {
    id: 'v12',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v12.png',
    alt: 'Vitrine commerciale 12',
    title: 'Vitrine 12',
    description: 'Création vitrine',
  },

  {
    id: 'v13',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v13.png',
    alt: 'Vitrine commerciale 13',
    title: 'Vitrine 13',
    description: 'Création vitrine',
  },
  {
    id: 'v14',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v14.png',
    alt: 'Vitrine commerciale 14',
    title: 'Vitrine 14',
    description: 'Création vitrine',
  },
  {
    id: 'v15',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v15.png',
    alt: 'Vitrine commerciale 15',
    title: 'Vitrine 15',
    description: 'Création vitrine',
  },

  {
    id: 'v109',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v109.png',
    alt: 'Vitrine commerciale 109',
    title: 'Vitrine 109',
    description: 'Création vitrine',
  },
  {
    id: 'v110',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v110.png',
    alt: 'Vitrine commerciale 110',
    title: 'Vitrine 110',
    description: 'Création vitrine',
  },
  {
    id: 'v111',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v111.png',
    alt: 'Vitrine commerciale 111',
    title: 'Vitrine 111',
    description: 'Création vitrine',
  },

  {
    id: 'v16',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v16.png',
    alt: 'Vitrine commerciale 16',
    title: 'Vitrine 16',
  },
  {
    id: 'v17',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v17.png',
    alt: 'Vitrine commerciale 17',
    title: 'Vitrine 17',
  },
  {
    id: 'v18',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v18.png',
    alt: 'Vitrine commerciale 18',
    title: 'Vitrine 18',
  },

  {
    id: 'v19',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v19.png',
    alt: 'Vitrine commerciale 19',
    title: 'Vitrine 19',
  },
  {
    id: 'v20',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v20.png',
    alt: 'Vitrine commerciale 20',
    title: 'Vitrine 20',
  },
  {
    id: 'v21',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v21.png',
    alt: 'Vitrine commerciale 21',
    title: 'Vitrine 21',
  },

  {
    id: 'v22',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v23.png',
    alt: 'Vitrine commerciale 22',
    title: 'Vitrine 22',
  },
  {
    id: 'v103',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v103.png',
    alt: 'Vitrine commerciale 103',
    title: 'Vitrine 103',
  },
  {
    id: 'v24',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v24.png',
    alt: 'Vitrine commerciale 24',
    title: 'Vitrine 24',
  },

  {
    id: 'v115',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v115.png',
    alt: 'Vitrine commerciale 115',
    title: 'Vitrine 115',
  },
  {
    id: 'v116',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v116.png',
    alt: 'Vitrine commerciale 116',
    title: 'Vitrine 116',
  },
  {
    id: 'v117',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v117.png',
    alt: 'Vitrine commerciale 117',
    title: 'Vitrine 117',
  },

  {
    id: 'v28',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v28.png',
    alt: 'Vitrine commerciale 28',
    title: 'Vitrine 28',
  },
  {
    id: 'v29',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v29.png',
    alt: 'Vitrine commerciale 29',
    title: 'Vitrine 29',
  },
  {
    id: 'v30',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v30.png',
    alt: 'Vitrine commerciale 30',
    title: 'Vitrine 30',
  },

  {
    id: 'v31',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v31.png',
    alt: 'Vitrine commerciale 31',
    title: 'Vitrine 31',
  },
  {
    id: 'v32',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v32.png',
    alt: 'Vitrine commerciale 32',
    title: 'Vitrine 32',
  },
  {
    id: 'v33',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v33.png',
    alt: 'Vitrine commerciale 33',
    title: 'Vitrine 33',
  },

  {
    id: 'v112',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v112.png',
    alt: 'Vitrine commerciale 112',
    title: 'Vitrine 112',
  },
  {
    id: 'v113',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v113.png',
    alt: 'Vitrine commerciale 113',
    title: 'Vitrine 113',
  },
  {
    id: 'v114',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v114.png',
    alt: 'Vitrine commerciale 114',
    title: 'Vitrine 114',
  },

  {
    id: 'v43',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v43.png',
    alt: 'Vitrine commerciale 43',
    title: 'Vitrine 43',
  },
  {
    id: 'v44',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v44.png',
    alt: 'Vitrine commerciale 44',
    title: 'Vitrine 44',
  },
  {
    id: 'v45',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v45.png',
    alt: 'Vitrine commerciale 45',
    title: 'Vitrine 45',
  },

  {
    id: 'v49',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v49.png',
    alt: 'Vitrine commerciale 49',
    title: 'Vitrine 49',
  },
  {
    id: 'v50',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v50.png',
    alt: 'Vitrine commerciale 50',
    title: 'Vitrine 50',
  },
  {
    id: 'v51',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v51.png',
    alt: 'Vitrine commerciale 51',
    title: 'Vitrine 51',
  },

  {
    id: 'v55',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v55.png',
    alt: 'Vitrine commerciale 55',
    title: 'Vitrine 55',
  },
  {
    id: 'v56',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v56.png',
    alt: 'Vitrine commerciale 56',
    title: 'Vitrine 56',
  },
  {
    id: 'v57',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v57.png',
    alt: 'Vitrine commerciale 57',
    title: 'Vitrine 57',
  },

  {
    id: 'v61',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v61.png',
    alt: 'Vitrine commerciale 61',
    title: 'Vitrine 61',
  },
  {
    id: 'v62',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v62.png',
    alt: 'Vitrine commerciale 62',
    title: 'Vitrine 62',
  },
  {
    id: 'v63',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v63.png',
    alt: 'Vitrine commerciale 63',
    title: 'Vitrine 63',
  },

  {
    id: 'v64',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v64.png',
    alt: 'Vitrine commerciale 64',
    title: 'Vitrine 64',
  },
  {
    id: 'v65',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v65.png',
    alt: 'Vitrine commerciale 65',
    title: 'Vitrine 65',
  },
  {
    id: 'v66',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v66.png',
    alt: 'Vitrine commerciale 66',
    title: 'Vitrine 66',
  },

  {
    id: 'v70',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v70.png',
    alt: 'Vitrine commerciale 70',
    title: 'Vitrine 70',
  },
  {
    id: 'v71',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v71.png',
    alt: 'Vitrine commerciale 71',
    title: 'Vitrine 71',
  },
  {
    id: 'v72',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v72.png',
    alt: 'Vitrine commerciale 72',
    title: 'Vitrine 72',
  },

  {
    id: 'v73',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v73.png',
    alt: 'Vitrine commerciale 73',
    title: 'Vitrine 73',
  },
  {
    id: 'v74',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v74.png',
    alt: 'Vitrine commerciale 74',
    title: 'Vitrine 74',
  },
  {
    id: 'v75',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v75.png',
    alt: 'Vitrine commerciale 75',
    title: 'Vitrine 75',
  },

  {
    id: 'v76',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v77.png',
    alt: 'Vitrine commerciale 76',
    title: 'Vitrine 76',
  },
  {
    id: 'v77',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v76.png',
    alt: 'Vitrine commerciale 77',
    title: 'Vitrine 77',
  },
  {
    id: 'v78',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v78.png',
    alt: 'Vitrine commerciale 78',
    title: 'Vitrine 78',
  },

  {
    id: 'v82',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v82.png',
    alt: 'Vitrine commerciale 82',
    title: 'Vitrine 82',
  },
  {
    id: 'v83',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v83.png',
    alt: 'Vitrine commerciale 83',
    title: 'Vitrine 83',
  },
  {
    id: 'v84',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v84.png',
    alt: 'Vitrine commerciale 84',
    title: 'Vitrine 84',
  },

  {
    id: 'v85',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v85.png',
    alt: 'Vitrine commerciale 85',
    title: 'Vitrine 85',
  },
  {
    id: 'v86',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v86.png',
    alt: 'Vitrine commerciale 86',
    title: 'Vitrine 86',
  },
  {
    id: 'v87',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v87.png',
    alt: 'Vitrine commerciale 87',
    title: 'Vitrine 87',
  },

  {
    id: 'v88',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v105.png',
    alt: 'Vitrine commerciale 88',
    title: 'Vitrine 88',
  },
  {
    id: 'v89',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v89b.png',
    alt: 'Vitrine commerciale 89',
    title: 'Vitrine 89',
  },
  {
    id: 'v90',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v90.png',
    alt: 'Vitrine commerciale 90',
    title: 'Vitrine 90',
  },

  {
    id: 'v94',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v94.png',
    alt: 'Vitrine commerciale 94',
    title: 'Vitrine 94',
  },
  {
    id: 'v95',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v95b.png',
    alt: 'Vitrine commerciale 95',
    title: 'Vitrine 95',
  },
  {
    id: 'v96',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v96.png',
    alt: 'Vitrine commerciale 96',
    title: 'Vitrine 96',
  },

  {
    id: 'v97',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v97.png',
    alt: 'Vitrine commerciale 97',
    title: 'Vitrine 97',
  },
  {
    id: 'v98',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v98.png',
    alt: 'Vitrine commerciale 98',
    title: 'Vitrine 98',
  },
  {
    id: 'v99',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v99.png',
    alt: 'Vitrine commerciale 99',
    title: 'Vitrine 99',
  },

  {
    id: 'v100',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v100.png',
    alt: 'Vitrine commerciale 100',
    title: 'Vitrine 100',
  },
  {
    id: 'v101',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v101.png',
    alt: 'Vitrine commerciale 101',
    title: 'Vitrine 101',
  },
  {
    id: 'v102',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v102.png',
    alt: 'Vitrine commerciale 102',
    title: 'Vitrine 102',
  },

  {
    id: 'v23',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v23b.png',
    alt: 'Vitrine commerciale 23',
    title: 'Vitrine 23',
  },
  {
    id: 'v104',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v104b.png',
    alt: 'Vitrine commerciale 104',
    title: 'Vitrine 104',
  },
  {
    id: 'v105',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v22.png',
    alt: 'Vitrine commerciale 105',
    title: 'Vitrine 105',
  },

  {
    id: 'v106',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v106.png',
    alt: 'Vitrine commerciale 106',
    title: 'Vitrine 106',
  },
  {
    id: 'v107',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v107.png',
    alt: 'Vitrine commerciale 107',
    title: 'Vitrine 107',
  },
  {
    id: 'v108',
    category: 'vitrines',
    src: '/images/gallery/vitrines/v108b.png',
    alt: 'Vitrine commerciale 108',
    title: 'Vitrine 108',
  },

  // --- Œuvres personnelles ---
  {
    id: 'o1',
    category: 'oeuvres',
    src: '/images/gallery/oeuvres/o1.jpg',
    alt: 'Œuvre personnelle 1',
    title: 'Œuvre 1',
  },
  {
    id: 'o2',
    category: 'oeuvres',
    src: '/images/gallery/oeuvres/o2.jpg',
    alt: 'Œuvre personnelle 2',
    title: 'Œuvre 2',
  },
  {
    id: 'o3',
    category: 'oeuvres',
    src: '/images/gallery/oeuvres/o3.jpg',
    alt: 'Œuvre personnelle 3',
    title: 'Œuvre 3',
  },
  {
    id: 'o4',
    category: 'oeuvres',
    src: '/images/gallery/oeuvres/o4.jpg',
    alt: 'Œuvre personnelle 4',
    title: 'Œuvre 4',
  },
  {
    id: 'o5',
    category: 'oeuvres',
    src: '/images/gallery/oeuvres/o5.jpg',
    alt: 'Œuvre personnelle 5',
    title: 'Œuvre 5',
  },
  {
    id: 'o6',
    category: 'oeuvres',
    src: '/images/gallery/oeuvres/o6.jpg',
    alt: 'Œuvre personnelle 6',
    title: 'Œuvre 6',
  },
  {
    id: 'o7',
    category: 'oeuvres',
    src: '/images/gallery/oeuvres/o7.jpg',
    alt: 'Œuvre personnelle 7',
    title: 'Œuvre 7',
  },
  {
    id: 'o8',
    category: 'oeuvres',
    src: '/images/gallery/oeuvres/o8.jpg',
    alt: 'Œuvre personnelle 8',
    title: 'Œuvre 8',
  },
  {
    id: 'o9',
    category: 'oeuvres',
    src: '/images/gallery/oeuvres/o9.jpg',
    alt: 'Œuvre personnelle 9',
    title: 'Œuvre 9',
  },

  // --- Communication animale ---
  {
    id: 'a1',
    category: 'animale',
    src: '/images/gallery/animale/a1.jpg',
    alt: 'TODO: Description visuel communication animale 1',
    title: 'Communication 1',
  },
  {
    id: 'a2',
    category: 'animale',
    src: '/images/gallery/animale/a2.jpg',
    alt: 'TODO: Description visuel communication animale 2',
    title: 'Communication 2',
  },

  // --- Autres créations ---
    {
      id: 'au1',
      category: 'autres',
      src: '/images/gallery/autres/au1.jpg',
      alt: 'Autre création 1',
      title: 'Création 1',
    },
    {
      id: 'au2',
      category: 'autres',
      src: '/images/gallery/autres/au2.jpeg',
      alt: 'Autre création 2',
      title: 'Création 2',
    },
    {
      id: 'au3',
      category: 'autres',
      src: '/images/gallery/autres/au3.jpeg',
      alt: 'Autre création 3',
      title: 'Création 3',
    },
    {
      id: 'au4',
      category: 'autres',
      src: '/images/gallery/autres/au4.jpeg',
      alt: 'Autre création 4',
      title: 'Création 4',
    },
    {
      id: 'au5',
      category: 'autres',
      src: '/images/gallery/autres/au5.jpeg',
      alt: 'Autre création 5',
      title: 'Création 5',
    },
    {
      id: 'au6',
      category: 'autres',
      src: '/images/gallery/autres/au6.jpeg',
      alt: 'Autre création 6',
      title: 'Création 6',
    },
    {
      id: 'au7',
      category: 'autres',
      src: '/images/gallery/autres/au7.jpeg',
      alt: 'Autre création 7',
      title: 'Création 7',
    },
    {
      id: 'au8',
      category: 'autres',
      src: '/images/gallery/autres/au8.jpeg',
      alt: 'Autre création 8',
      title: 'Création 8',
    },
    {
      id: 'au9',
      category: 'autres',
      src: '/images/gallery/autres/au9.jpeg',
      alt: 'Autre création 9',
      title: 'Création 9',
    },
    {
      id: 'au10',
      category: 'autres',
      src: '/images/gallery/autres/au10.jpeg',
      alt: 'Autre création 10',
      title: 'Création 10',
    },
    {
      id: 'au11',
      category: 'autres',
      src: '/images/gallery/autres/au11.jpg',
      alt: 'Autre création 11',
      title: 'Création 11',
    },
    {
      id: 'au12',
      category: 'autres',
      src: '/images/gallery/autres/au12.jpg',
      alt: 'Autre création 12',
      title: 'Création 12',
    },
    {
      id: 'au13',
      category: 'autres',
      src: '/images/gallery/autres/au13.jpg',
      alt: 'Autre création 13',
      title: 'Création 13',
    },
    {
      id: 'au14',
      category: 'autres',
      src: '/images/gallery/autres/au14.jpg',
      alt: 'Autre création 14',
      title: 'Création 14',
    },
    {
      id: 'au15',
      category: 'autres',
      src: '/images/gallery/autres/au15.jpg',
      alt: 'Autre création 15',
      title: 'Création 15',
    },
    {
      id: 'au16',
      category: 'autres',
      src: '/images/gallery/autres/au16.jpg',
      alt: 'Autre création 16',
      title: 'Création 16',
    },
    {
      id: 'au17',
      category: 'autres',
      src: '/images/gallery/autres/au17.jpeg',
      alt: 'Autre création 17',
      title: 'Création 17',
    },
    {
      id: 'au18',
      category: 'autres',
      src: '/images/gallery/autres/au18.jpeg',
      alt: 'Autre création 18',
      title: 'Création 18',
    },
    {
      id: 'au19',
      category: 'autres',
      src: '/images/gallery/autres/au19.jpeg',
      alt: 'Autre création 19',
      title: 'Création 19',
    },
    {
      id: 'au20',
      category: 'autres',
      src: '/images/gallery/autres/au20.jpg',
      alt: 'Autre création 20',
      title: 'Création 20',
    },
    {
      id: 'au21',
      category: 'autres',
      src: '/images/gallery/autres/au21.jpg',
      alt: 'Autre création 21',
      title: 'Création 21',
    },
    {
      id: 'au22',
      category: 'autres',
      src: '/images/gallery/autres/au22.jpg',
      alt: 'Autre création 22',
      title: 'Création 22',
    },
    {
      id: 'au23',
      category: 'autres',
      src: '/images/gallery/autres/au23.jpg',
      alt: 'Autre création 23',
      title: 'Création 23',
    },
    {
      id: 'au24',
      category: 'autres',
      src: '/images/gallery/autres/au24.jpg',
      alt: 'Autre création 24',
      title: 'Création 24',
    },
    {
      id: 'au25',
      category: 'autres',
      src: '/images/gallery/autres/au25.jpg',
      alt: 'Autre création 25',
      title: 'Création 25',
    },
    {
      id: 'au26',
      category: 'autres',
      src: '/images/gallery/autres/au26.jpeg',
      alt: 'Autre création 26',
      title: 'Création 26',
    },
    {
      id: 'au27',
      category: 'autres',
      src: '/images/gallery/autres/au27.jpeg',
      alt: 'Autre création 27',
      title: 'Création 27',
    },
    {
      id: 'au28',
      category: 'autres',
      src: '/images/gallery/autres/au28.jpg',
      alt: 'Autre création 28',
      title: 'Création 28',
    },
    {
      id: 'au29',
      category: 'autres',
      src: '/images/gallery/autres/au29.jpeg',
      alt: 'Autre création 29',
      title: 'Création 29',
    },
    {
      id: 'au30',
      category: 'autres',
      src: '/images/gallery/autres/au30.jpeg',
      alt: 'Autre création 30',
      title: 'Création 30',
    },
    {
      id: 'au31',
      category: 'autres',
      src: '/images/gallery/autres/au31.jpeg',
      alt: 'Autre création 31',
      title: 'Création 31',
    },
    {
      id: 'au32',
      category: 'autres',
      src: '/images/gallery/autres/au32.jpeg',
      alt: 'Autre création 32',
      title: 'Création 32',
    },
    {
      id: 'au33',
      category: 'autres',
      src: '/images/gallery/autres/au33.jpeg',
      alt: 'Autre création 33',
      title: 'Création 33',
    },
    {
      id: 'au34',
      category: 'autres',
      src: '/images/gallery/autres/au34.jpeg',
      alt: 'Autre création 34',
      title: 'Création 34',
    },
    {
      id: 'au35',
      category: 'autres',
      src: '/images/gallery/autres/au35.jpg',
      alt: 'Autre création 35',
      title: 'Création 35',
    },
    {
      id: 'au36',
      category: 'autres',
      src: '/images/gallery/autres/au36.jpg',
      alt: 'Autre création 36',
      title: 'Création 36',
    },
    {
      id: 'au37',
      category: 'autres',
      src: '/images/gallery/autres/au37.jpg',
      alt: 'Autre création 37',
      title: 'Création 37',
    },
    {
      id: 'au38',
      category: 'autres',
      src: '/images/gallery/autres/au38.jpg',
      alt: 'Autre création 38',
      title: 'Création 38',
    },
    {
      id: 'au39',
      category: 'autres',
      src: '/images/gallery/autres/au39.jpg',
      alt: 'Autre création 39',
      title: 'Création 39',
    },
    {
      id: 'au40',
      category: 'autres',
      src: '/images/gallery/autres/au40.jpg',
      alt: 'Autre création 40',
      title: 'Création 40',
    },
    {
      id: 'au41',
      category: 'autres',
      src: '/images/gallery/autres/au41.jpg',
      alt: 'Autre création 41',
      title: 'Création 41',
    },
    {
      id: 'au42',
      category: 'autres',
      src: '/images/gallery/autres/au42.jpg',
      alt: 'Autre création 42',
      title: 'Création 42',
    },
    {
      id: 'au43',
      category: 'autres',
      src: '/images/gallery/autres/au43.jpeg',
      alt: 'Autre création 43',
      title: 'Création 43',
    },
    {
      id: 'au44',
      category: 'autres',
      src: '/images/gallery/autres/au44.jpeg',
      alt: 'Autre création 44',
      title: 'Création 44',
    },
    {
      id: 'au45',
      category: 'autres',
      src: '/images/gallery/autres/au45.jpg',
      alt: 'Autre création 45',
      title: 'Création 45',
    },
    {
      id: 'au46',
      category: 'autres',
      src: '/images/gallery/autres/au46.jpg',
      alt: 'Autre création 46',
      title: 'Création 46',
    },
    {
      id: 'au47',
      category: 'autres',
      src: '/images/gallery/autres/au47.jpg',
      alt: 'Autre création 47',
      title: 'Création 47',
    },
    {
      id: 'au48',
      category: 'autres',
      src: '/images/gallery/autres/au48.jpg',
      alt: 'Autre création 48',
      title: 'Création 48',
    },
    {
      id: 'au49',
      category: 'autres',
      src: '/images/gallery/autres/au49.jpg',
      alt: 'Autre création 49',
      title: 'Création 49',
    },
    {
      id: 'au50',
      category: 'autres',
      src: '/images/gallery/autres/au50.jpeg',
      alt: 'Autre création 50',
      title: 'Création 50',
    },
    {
      id: 'au51',
      category: 'autres',
      src: '/images/gallery/autres/au51.jpg',
      alt: 'Autre création 51',
      title: 'Création 51',
    },
    {
      id: 'au52',
      category: 'autres',
      src: '/images/gallery/autres/au52.jpg',
      alt: 'Autre création 52',
      title: 'Création 52',
    },
    {
      id: 'au53',
      category: 'autres',
      src: '/images/gallery/autres/au53.jpg',
      alt: 'Autre création 53',
      title: 'Création 53',
    },
    {
      id: 'au54',
      category: 'autres',
      src: '/images/gallery/autres/au54.jpg',
      alt: 'Autre création 54',
      title: 'Création 54',
    },
    {
      id: 'au55',
      category: 'autres',
      src: '/images/gallery/autres/au55.jpg',
      alt: 'Autre création 55',
      title: 'Création 55',
    },
    {
      id: 'au56',
      category: 'autres',
      src: '/images/gallery/autres/au56.jpg',
      alt: 'Autre création 56',
      title: 'Création 56',
    },
    {
      id: 'au57',
      category: 'autres',
      src: '/images/gallery/autres/au57.jpg',
      alt: 'Autre création 57',
      title: 'Création 57',
    },
    {
      id: 'au58',
      category: 'autres',
      src: '/images/gallery/autres/au58.jpg',
      alt: 'Autre création 58',
      title: 'Création 58',
    },
    {
      id: 'au59',
      category: 'autres',
      src: '/images/gallery/autres/au59.jpeg',
      alt: 'Autre création 59',
      title: 'Création 59',
    },
    {
      id: 'au60',
      category: 'autres',
      src: '/images/gallery/autres/au60.jpg',
      alt: 'Autre création 60',
      title: 'Création 60',
    },
    {
      id: 'au61',
      category: 'autres',
      src: '/images/gallery/autres/au61.jpg',
      alt: 'Autre création 61',
      title: 'Création 61',
    },
    {
      id: 'au62',
      category: 'autres',
      src: '/images/gallery/autres/au62.jpeg',
      alt: 'Autre création 62',
      title: 'Création 62',
    },
    {
      id: 'au63',
      category: 'autres',
      src: '/images/gallery/autres/au63.jpeg',
      alt: 'Autre création 63',
      title: 'Création 63',
    },
    {
      id: 'au64',
      category: 'autres',
      src: '/images/gallery/autres/au64.jpeg',
      alt: 'Autre création 64',
      title: 'Création 64',
    },
    {
      id: 'au65',
      category: 'autres',
      src: '/images/gallery/autres/au65.jpeg',
      alt: 'Autre création 65',
      title: 'Création 65',
    },
    {
      id: 'au66',
      category: 'autres',
      src: '/images/gallery/autres/au66.jpeg',
      alt: 'Autre création 66',
      title: 'Création 66',
    },
    {
      id: 'au67',
      category: 'autres',
      src: '/images/gallery/autres/au67.jpg',
      alt: 'Autre création 67',
      title: 'Création 67',
    },
    {
      id: 'au68',
      category: 'autres',
      src: '/images/gallery/autres/au68.jpg',
      alt: 'Autre création 68',
      title: 'Création 68',
    },
    {
      id: 'au69',
      category: 'autres',
      src: '/images/gallery/autres/au69.jpg',
      alt: 'Autre création 69',
      title: 'Création 69',
    },
    {
      id: 'au70',
      category: 'autres',
      src: '/images/gallery/autres/au70.jpg',
      alt: 'Autre création 70',
      title: 'Création 70',
    },
    {
      id: 'au71',
      category: 'autres',
      src: '/images/gallery/autres/au71.jpg',
      alt: 'Autre création 71',
      title: 'Création 71',
    },
    {
      id: 'au72',
      category: 'autres',
      src: '/images/gallery/autres/au72.jpg',
      alt: 'Autre création 72',
      title: 'Création 72',
    },
    {
      id: 'au73',
      category: 'autres',
      src: '/images/gallery/autres/au73.jpg',
      alt: 'Autre création 73',
      title: 'Création 73',
    },
    {
      id: 'au74',
      category: 'autres',
      src: '/images/gallery/autres/au74.jpg',
      alt: 'Autre création 74',
      title: 'Création 74',
    },
    {
      id: 'au75',
      category: 'autres',
      src: '/images/gallery/autres/au75.jpg',
      alt: 'Autre création 75',
      title: 'Création 75',
    },
    {
      id: 'au76',
      category: 'autres',
      src: '/images/gallery/autres/au76.jpeg',
      alt: 'Autre création 76',
      title: 'Création 76',
    },
    {
      id: 'au77',
      category: 'autres',
      src: '/images/gallery/autres/au77.jpeg',
      alt: 'Autre création 77',
      title: 'Création 77',
    },
    {
      id: 'au78',
      category: 'autres',
      src: '/images/gallery/autres/au78.jpeg',
      alt: 'Autre création 78',
      title: 'Création 78',
    },
    {
      id: 'au79',
      category: 'autres',
      src: '/images/gallery/autres/au79.jpg',
      alt: 'Autre création 79',
      title: 'Création 79',
    },
    {
      id: 'au80',
      category: 'autres',
      src: '/images/gallery/autres/au80.jpg',
      alt: 'Autre création 80',
      title: 'Création 80',
    },
]

export const galleryCategories = [
  { key: 'all' as const, label: 'Tout' },
  { key: 'vitrines' as GalleryCategory, label: 'Vitrines' },
  { key: 'oeuvres' as GalleryCategory, label: 'Œuvres personnelles' },
  { key: 'animale' as GalleryCategory, label: 'Communication animale' },
  { key: 'autres' as GalleryCategory, label: 'Autres créations' },
  { key: 'edition-limitee' as GalleryCategory, label: 'Édition limitée' },
]
